interval = 1200
request_timeout = 300
data_path = "config/"

[credential]
sessdata = ""
bili_jct = ""
buvid3 = ""
dedeuserid = ""
ac_time_value = ""


[favorite_list]
# 键值对存储，key是收藏夹id，value是下载存储路径
# fid = "<download_path>"
-1="sync/"